//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoAn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DeTai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeTai()
        {
            this.HuongDans = new HashSet<HuongDan>();
            this.SinhViens = new HashSet<SinhVien>();
        }
        [DisplayName("Mã Đề Tài")]
        public string maDeTai { get; set; }
        [DisplayName("Tên Đề Tài")]
        public string tenDeTai { get; set; }
        [DisplayName("Số Sinh Viên Tham Gia")]
        public Nullable<int> soSVThamGia { get; set; }
        [DisplayName("Ghi Chú")]
        public string ghiChu { get; set; }
        [DisplayName("Số Sinh Viên Đã Đăng Kí")]
        public Nullable<int> soSVDaDangKy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HuongDan> HuongDans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien> SinhViens { get; set; }
    }
}
