//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoAn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class GiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiangVien()
        {
            this.HuongDans = new HashSet<HuongDan>();
        }
        [DisplayName("Mã Giảng Viên")]
        public string maGiangVien { get; set; }
        [DisplayName("Tên Giảng Viên")]
        public string tenGiangVien { get; set; }
        public string email { get; set; }
        [DisplayName("Số Điện Thoại")]
        public string soDienThoai { get; set; }
        [DisplayName("Ngày Sinh")]
        public Nullable<System.DateTime> ngaySinh { get; set; }
        [DisplayName("Giới Tính")]
        public string gioiTinh { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HuongDan> HuongDans { get; set; }
    }
}
