//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoAn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HuongDan
    {
        [DisplayName("Mã Giảng Viên")]
        public string maGiangVien { get; set; }
        [DisplayName("Mã Đề Tài")]
        public string maDeTai { get; set; }
        [DisplayName("Nhận Xét")]
        public string nhanXet { get; set; }
        [DisplayName("Điểm")]
        public Nullable<double> diemDeTai { get; set; }
    
        public virtual DeTai DeTai { get; set; }
        public virtual GiangVien GiangVien { get; set; }
    }
}
