//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoAn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class QuanTri
    {
        [DisplayName("Mã Admin")]
        public string maQuanLy { get; set; }
        [DisplayName("Tên Admin")]
        public string tenQuanLy { get; set; }
        [DisplayName("Giới Tính")]
        public string gioiTinh { get; set; }
        public string email { get; set; }
        [DisplayName("Số Điện Thoại")]
        public string soDienThoai { get; set; }
        [DisplayName("Ngày Sinh")]
        public Nullable<System.DateTime> ngaySinh { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
